#!/usr/bin/env node
/**
 * Bundle the `reviews` CLI (scripts/reviews.mjs + src/pure.ts + yaml) into one
 * dependency-free Node file, so it runs outside this clone: shipped inside the
 * Claude Code plugin (plugins/review-md/bin/) and attached to each GitHub release.
 *
 * The bundle is committed (a plugin installs straight from git, no build step), so
 * `--check` rebuilds in memory and fails when the committed copy is stale — part
 * of `make check`.
 *
 * Run:  node scripts/build-cli.mjs            (or: make cli)
 *       node scripts/build-cli.mjs --check    (or: make cli-check)
 */
import esbuild from "esbuild";
import { readFileSync, existsSync } from "node:fs";
import { resolve, join, relative } from "node:path";

const repo = resolve(import.meta.dirname, "..");
export const CLI_OUT = join(repo, "plugins/review-md/bin/reviews.mjs");
const check = process.argv.includes("--check");

const result = await esbuild.build({
  entryPoints: [join(repo, "scripts/reviews.mjs")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  // Path comments in the bundle must not depend on the checkout: a worktree whose
  // node_modules is a symlink would otherwise embed the link's target and fail --check.
  preserveSymlinks: true,
  banner: {
    // esbuild keeps the entry's own #! line above this banner. yaml is CommonJS and
    // requires node builtins, which an ESM bundle can't do without a real require.
    js: [
      "// GENERATED by scripts/build-cli.mjs from scripts/reviews.mjs — edit the source, then `make cli`.",
      'import { createRequire as __createRequire } from "node:module";',
      "const require = __createRequire(import.meta.url);",
    ].join("\n"),
  },
  legalComments: "none",
  write: !check,
  outfile: CLI_OUT,
  logLevel: check ? "silent" : "info",
});

if (check) {
  const fresh = result.outputFiles[0].text;
  const committed = existsSync(CLI_OUT) ? readFileSync(CLI_OUT, "utf8") : "";
  if (fresh !== committed) {
    console.error(`cli-check: ${relative(repo, CLI_OUT)} is stale — run \`make cli\` and commit it`);
    process.exit(1);
  }
  console.log(`cli-check: ${relative(repo, CLI_OUT)} is up to date`);
}
